### ISSUE TITLE
AssetsManager->copyAssets() why asset has to start with APP_ROOT? 

### ISSUE THREAD

**Issue by ricco24** [remp2020/crm-application-module#4]
I want to run tests of new modules with codeception. I made dummy CRM in tests subdirectory. It seems everything working except this. I dont understant why asset has to be in APP_ROOT.

If it is because of security, is possible to move check to InstallAssetsCommand and remove from registration?

**Comment by rootpd** [comment]
Hi, I believe this is already sorted out. Me and @mikoczy had a discussion about this off-github and it should be possible to run tests even with the current setup. We run our tests from within `./tests` folder and our `./tests/bootstrap.php` has this in the beginning:

```php
$core = new \Crm\ApplicationModule\Core(realpath(dirname($_SERVER["SCRIPT_FILENAME"]) . '/../../'));
```

That should do the trick to have correct app root within the project.

For anyone coming here, the reason why there's a limitation about where the assets can be copied, it's a security feature to forbid malicious CRM modules to copy custom files outside of the project onto the filesystem.

If there's still any other issue, let me know and we can reopen this.
